spring.application.name=zidioBackend

#Database Configuration
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=system
spring.datasource.password=ashStoic143
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.datasource-platform=org.hibernate.dialect.Oracle12Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

## Google
#spring.security.oauth2.client.registration.google.client-id=642218105077-p7r09b827t4me94mi6apeg8veu0upi5u.apps.googleusercontent.com
#spring.security.oauth2.client.registration.google.client-secret=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
#spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/google
#spring.security.oauth2.client.registration.google.scope=openid,profile,email
#
## GitHub
#spring.security.oauth2.client.registration.github.client-id=Ov23litqdlxn38Fhzcaq
#spring.security.oauth2.client.registration.github.client-secret=6654d782edd9c23d159402a3abdf2817b2536f62
#spring.security.oauth2.client.registration.github.redirect-uri={baseUrl}/login/oauth2/code/github
#spring.security.oauth2.client.registration.github.scope=user:email
#
## Set your frontend URL
#app.frontend.url=http://localhost:3000